stages:
  - test
  - docs

pylint:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse ./lint.sh wildland -v

pytest:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - mkdir --mode=0777 htmlcov
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse ./test.sh -v --cov=wildland --cov-report term --cov-report html
  artifacts:
    paths:
      - htmlcov/
  coverage: '/TOTAL.*\s(\d+)%/'

examples:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - mkdir --mode=0777 htmlcov
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse < /dev/null
  artifacts:
    paths:
      - htmlcov/
  coverage: '/TOTAL.*\s(\d+)%/'

pages-test:
  stage: docs
  except:
    - master
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - mkdir --mode=0777 Documentation/_build
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse make -C /wildland-fuse/Documentation html SPHINXOPTS=-W SPHINXBUILD=/home/user/env/bin/sphinx-build

pages:
  stage: docs
  dependencies:
    - pytest
  only:
    - master
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - mkdir --mode=0777 Documentation/_build
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse make -C /wildland-fuse/Documentation html SPHINXOPTS=-W SPHINXBUILD=/home/user/env/bin/sphinx-build
    - cp -r ../Documentation/_build/html ../public
    - cp -r ../htmlcov ../public/coverage
  artifacts:
    paths:
      - public/
