stages:
  - build
  - test
  - docs

before_script:
  - mkdir -p --mode=0777 artifacts artifacts/htmlcov

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_TEST_IMAGE_IMAP: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-imap
  CONTAINER_TEST_IMAGE_HOWTO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-howto
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd ci
    - docker-compose build
    - docker tag wildland-client-ci $CONTAINER_TEST_IMAGE
    - docker tag wildland-client-ci-imap $CONTAINER_TEST_IMAGE_IMAP
    - docker tag wildland-client-ci-howto $CONTAINER_TEST_IMAGE_HOWTO
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_TEST_IMAGE_IMAP
    - docker push $CONTAINER_TEST_IMAGE_HOWTO

lint:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-lint

mypy:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-mypy wildland
  artifacts:
    reports:
      junit: artifacts/wildland-mypy.xml

mypy-plugins:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-mypy --junit-xml artifacts/wildland-mypy-plugins.xml plugins
  artifacts:
    reports:
      junit: artifacts/wildland-mypy-plugins.xml

pytest:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - export PYTEST_ADDOPTS="--color=yes"
    - ./ci/ci-pytest
  artifacts:
    paths:
      - artifacts/htmlcov/
    reports:
      junit: artifacts/wildland.xml
      cobertura: artifacts/coverage.xml
  coverage: '/TOTAL.*\s(\d+)%/'

bear-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/wildland-test-runner.sh ./ci/ci-bear

gitlab-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-gitlab-test

git-test:
    stage: test
    image: $CONTAINER_TEST_IMAGE
    script:
        - ./ci/ci-git-test

gitlab-graphql-test:
    stage: test
    image: $CONTAINER_TEST_IMAGE
    script:
      - ./ci/ci-gitlab-graphql-test

imap-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE_IMAP
  script:
    - ./ci/ci-imap-test

ipfs-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-ipfs

s3-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-s3

encrypted-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-encrypted

dropbox-test-legacy:
  allow_failure: true
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-dropbox "$DROPBOX_TEST_ACCESS_TOKEN"

dropbox-test:
  allow_failure: true
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-dropbox "" "$DROPBOX_TEST_APP_KEY" "$DROPBOX_TEST_REFRESH_TOKEN"

googledrive-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-googledrive "$GOOGLEDRIVE_TEST_ACCESS_TOKEN"

howto-quick-start-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE_HOWTO
  script:
    - ./ci/howto-quick-start

howto-sharing-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE_HOWTO
  script:
    - ./ci/howto-sharing-and-access-control

howto-forest-creation-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE_HOWTO
  script:
    - ./ci/howto-forest-creation

howto-group-users-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE_HOWTO
  script:
    - ./ci/howto-group-users

howto-encryption-backend-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE_HOWTO
  script:
    - ./ci/howto-encryption-backend

smoke-test:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - ./wildland-docker.sh wl-smoke-test < /dev/null

pages-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  except:
    - master
  script:
    - ./ci/ci-docs
  artifacts:
    paths:
      - artifacts/docs

pages:
  stage: docs
  image: $CONTAINER_TEST_IMAGE
  dependencies:
    - pytest
  only:
    - master
  script:
    - ./ci/ci-docs
    - cp -r artifacts/docs/html public
    - cp -r artifacts/docs/man public/man
    - cp -r artifacts/htmlcov public/coverage
  artifacts:
    paths:
      - public/
