stages:
  - test

pylint:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse lint.sh wildland -v

pytest:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse test.sh -v
