stages:
  - test
  - docs

pylint:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse lint.sh wildland -v

pytest:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse test.sh -v

sphinx:
  stage: docs
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse make -C /wildland-fuse/Documentation html SPHINXOPTS=-W
