stages:
  - test
  - docs

lint:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd ci
    - docker-compose build
    - docker-compose run wildland-fuse-ci ./ci/ci-lint

pytest:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - mkdir --mode=0777 htmlcov/
    - cd ci
    - docker-compose build
    - docker-compose run wildland-fuse-ci ./ci/ci-pytest
  artifacts:
    paths:
      - htmlcov/
  coverage: '/TOTAL.*\s(\d+)%/'

examples:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd demo
    - docker-compose build
    - docker-compose run wildland-fuse wl-example < /dev/null

pages-test:
  stage: docs
  image: docker/compose:latest
  except:
    - master
  services:
    - docker:dind
  script:
    - mkdir --mode=0777 Documentation/_build
    - cd ci
    - docker-compose build
    - docker-compose run wildland-fuse-ci ./ci/ci-docs

pages:
  stage: docs
  image: docker/compose:latest
  dependencies:
    - pytest
  only:
    - master
  services:
    - docker:dind
  script:
    - mkdir --mode=0777 Documentation/_build
    - cd ci
    - docker-compose build
    - docker-compose run wildland-fuse-ci ./ci/ci-docs
  artifacts:
    paths:
      - public/
