stages:
  - test
  - docs

lint:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd ci
    - docker-compose build
    - docker-compose run wildland-fuse-ci ./ci/ci-lint

pytest:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - mkdir -p --mode=0777 artifacts artifacts/htmlcov
    - cd ci
    - docker-compose build
    - docker-compose run wildland-fuse-ci ./ci/ci-pytest
  artifacts:
    paths:
      - artifacts/htmlcov/
    reports:
      junit: artifacts/wildland.xml
  coverage: '/TOTAL.*\s(\d+)%/'

bear-test:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd ci
    - docker-compose build
    - docker-compose run wildland-fuse-ci ./ci/ci-bear-test

smoke-test:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd docker
    - docker-compose build
    - docker-compose run wildland-fuse wl-smoke-test < /dev/null

pages-test:
  stage: docs
  image: docker/compose:latest
  except:
    - master
  services:
    - docker:dind
  script:
    - mkdir -p --mode=0777 artifacts artifacts/docs
    - cd ci
    - docker-compose build
    - docker-compose run wildland-fuse-ci ./ci/ci-docs
  artifacts:
    paths:
      - artifacts/docs

pages:
  stage: docs
  image: docker/compose:latest
  dependencies:
    - pytest
  only:
    - master
  services:
    - docker:dind
  script:
    - mkdir -p --mode=0777 artifacts artifacts/docs
    - cd ci
    - docker-compose build
    - docker-compose run wildland-fuse-ci ./ci/ci-docs
    - cp -r ../artifacts/docs/html ../public
    - cp -r ../artifacts/docs/man ../public/man
    - cp -r ../artifacts/htmlcov ../public/coverage
  artifacts:
    paths:
      - public/
