stages:
  - build
  - test
  - docs

before_script:
  - mkdir -p --mode=0777 artifacts artifacts/docs artifacts/htmlcov

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-ci
  CONTAINER_IMAGE_DEV: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - cd docker
    - docker-compose build wildland-client-base
    - docker-compose build --parallel wildland-client wildland-client-ci
    - docker tag wildland-client-ci $CONTAINER_TEST_IMAGE
    - docker tag wildland-client $CONTAINER_IMAGE_DEV
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_IMAGE_DEV

gcp:
  stage: build
  image: docker/compose:latest
  when: manual
  allow_failure: true
  services:
    - docker:dind
  script:
    - echo $CI_COMMIT_SHA > git_commit_sha.txt
    - cd docker
    - docker-compose build wildland-client-base
    - docker-compose build wildland-client-gcp
    - docker tag wildland-client-gcp:latest eu.gcr.io/single-bindery-317213/wildland-client-gcp:latest
    - echo $GCP_DOCKER_REPO_JSON | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
    - docker push eu.gcr.io/single-bindery-317213/wildland-client-gcp:latest

lint:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-lint

mypy-wildland:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-mypy-wildland
  artifacts:
    reports:
      junit: artifacts/wildland-mypy.xml

mypy-plugins:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-mypy-plugins
  artifacts:
    reports:
      junit: artifacts/wildland-mypy-plugins.xml

pytest:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - export PYTEST_ADDOPTS="--color=yes"
    - ./ci/ci-pytest
  after_script:
    - /home/user/env/bin/python3 -m coverage combine
    - /home/user/env/bin/python3 -m coverage xml -o artifacts/coverage.xml
    - /home/user/env/bin/python3 -m coverage html -d artifacts/htmlcov
    - /home/user/env/bin/python3 -m coverage report --include=wildland/* --omit=wildland/storage_backends/transpose.py
    - sed -i -e '/<source><\/source>/d' artifacts/coverage.xml
  coverage: '/TOTAL.*\s(\d+)%/'
  artifacts:
    when: always
    paths:
      - artifacts/htmlcov/
      - artifacts/sync-daemon.log
    reports:
      junit: artifacts/wildland.xml
      cobertura: artifacts/coverage.xml

transpose-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-transpose
  after_script:
    - /home/user/env/bin/python3 -m coverage combine
    - /home/user/env/bin/python3 -m coverage xml -o artifacts/coverage.xml
    - /home/user/env/bin/python3 -m coverage report --include=wildland/storage_backends/transpose.py
    - sed -i -e '/<source><\/source>/d' artifacts/coverage.xml
  coverage: '/TOTAL.*\s(\d+)%/'
  artifacts:
    reports:
      cobertura: artifacts/coverage.xml

.plugin_test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  after_script:
    - /home/user/env/bin/python3 -m coverage combine
    - /home/user/env/bin/python3 -m coverage xml -o artifacts/coverage.xml
    - /home/user/env/bin/python3 -m coverage report --include=plugins/${CI_JOB_NAME%-test*}/*
    - sed -i -e '/<source><\/source>/d' artifacts/coverage.xml
  coverage: '/TOTAL.*\s(\d+)%/'
  artifacts:
    reports:
      cobertura: artifacts/coverage.xml

bearnotes-test:
  extends: .plugin_test
  script:
    - ./ci/wildland-test-runner.sh ./ci/ci-bearnotes

categorization-proxy-test:
  extends: .plugin_test
  script:
    - ./ci/ci-categorization-proxy

gitlab-test:
  extends: .plugin_test
  script:
    - ./ci/ci-gitlab

git-test:
  extends: .plugin_test
  script:
    - ./ci/ci-git

gitlab-graphql-test:
  extends: .plugin_test
  script:
    - ./ci/ci-gitlab-graphql

imap-test:
  extends: .plugin_test
  script:
    - ./ci/ci-imap

ipfs-test:
  extends: .plugin_test
  script:
    - ./ci/ci-ipfs

jira-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-jira

sshfs-test:
  extends: .plugin_test
  script:
    - ./ci/ci-sshfs

s3-test:
  extends: .plugin_test
  script:
    - ./ci/ci-s3

redis-test:
  extends: .plugin_test
  script:
    - ./ci/ci-redis

webdav-test:
    extends: .plugin_test
    script:
      - ./ci/ci-webdav

encrypted-test:
  extends: .plugin_test
  script:
    - ./ci/ci-encrypted

dropbox-test-legacy:
  extends: .plugin_test
  allow_failure: true
  script:
    - ./ci/ci-dropbox "$DROPBOX_TEST_ACCESS_TOKEN"

dropbox-test:
  extends: .plugin_test
  script:
    - ./ci/ci-dropbox "" "$DROPBOX_TEST_APP_KEY" "$DROPBOX_TEST_REFRESH_TOKEN"

googledrive-test:
  extends: .plugin_test
  # until https://gitlab.com/wildland/wildland-client/-/issues/730 is fixed
  allow_failure: true
  script:
    - ./ci/ci-googledrive "$GOOGLEDRIVE_TEST_ACCESS_TOKEN"

zip-archive-test:
  extends: .plugin_test
  script:
    - ./ci/ci-zip-archive

howto-quick-start-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/howto-quick-start

howto-sharing-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/howto-sharing-and-access-control

howto-forest-creation-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/howto-forest-creation

howto-group-users-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/howto-group-users

howto-encryption-backend-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/howto-encryption-backend

howto-cache-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - timeout 15m ./ci/howto-cache
  artifacts:
    when: always
    paths:
      - artifacts/sync-daemon.log

user-directory-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/howto-user-directory

group-users-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/howto-group-users-with-user-path

smoke-test:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - ./wildland-docker.sh ci/ci-smoke-test < /dev/null

pages-test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  except:
    - master
  script:
    - ./ci/ci-docs
  artifacts:
    paths:
      - artifacts/docs

pages:
  stage: docs
  image: $CONTAINER_TEST_IMAGE
  dependencies:
    - pytest
  only:
    - master
  script:
    - ./ci/ci-docs
    - cp -r artifacts/docs/html public
    - cp -r artifacts/docs/man public/man
    - cp -r artifacts/htmlcov public/coverage
  artifacts:
    paths:
      - public/

subcontainer-remounter:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ./ci/ci-remounter
