version: '3'

services:
  wildland-client:
    image: registry.gitlab.com/wildland/wildland-client:${CI_COMMIT_REF_SLUG:-master}
    container_name: wildland-client
    privileged: true
    stdin_open: true
    hostname: wildland-client
    tty: true
    devices:
      - /dev/fuse
    ports:
      - "8080:8080"
    volumes:
      - ~/.config/wildland:/home/user/.config/wildland:rw
      - ./docker/storage:/home/user/storage:rw
