signer: "user"
signature: "dummy.user"
---

signer: user

paths:
  - /container2
  - /test/a2
  - /test/a1/b/a2

backends:
  storage:
    - storage21.yaml
    - storage22.yaml

# vim: ts=2 sts=2 sw=2 et
