signer: "user"
signature: "dummy.user"
---

signer: user
uuid: "fbc4d1a0-75a7-11ea-8e21-00163e5e6c00"

paths:
  - /container1
  - /test/a1

backends:
  storage:
    - storage11.yaml
    - storage12.yaml

# vim: ts=2 sts=2 sw=2 et
