version: '3'

services:
  wildland-fuse-ci:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
    image: wildland-fuse-ci
    container_name: wildland-fuse-ci

  wildland-fuse:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: wildland-fuse
    image: wildland-fuse
    depends_on:
      - wildland-fuse-ci
    privileged: true
    stdin_open: true
    tty: true
    devices:
      - /dev/fuse
    ports:
      - "8080:8080"
      - "445:445"
      - "139:139"
    volumes:
      - ..:/home/user/wildland-fuse:ro
      - usercfg:/home/user/.config:rw
      - ./storage:/home/user/storage:rw

volumes:
  usercfg:
