version: '3'

services:
  wildland-client-ci:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
    image: wildland-client-ci
    container_name: wildland-client-ci

  wildland-client:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: wildland-client
    image: wildland-client
    depends_on:
      - wildland-client-ci
    privileged: true
    stdin_open: true
    tty: true
    devices:
      - /dev/fuse
    ports:
      - "8080:8080"
      - "445:445"
      - "139:139"
    volumes:
      - ..:/home/user/wildland-client:ro
      - ~/.config/wildland:/home/user/.config/wildland:rw
      - ./storage:/home/user/storage:rw

  wildland-forest:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.forest
    container_name: wildland-forest
    image: wildland-forest
    depends_on:
      - wildland-client
    privileged: true
    stdin_open: true
    tty: true
    devices:
      - /dev/fuse
    ports:
      - "8080:8080"
      - "445:445"
      - "139:139"
    volumes:
      - ..:/home/user/wildland-client:ro
      - usercfg:/home/user/.config:rw
      - ./storage:/home/user/storage:rw

volumes:
  usercfg:
