# This image is used to try out implementing HL wildland tool

FROM wildland-client

USER root

RUN apt-get -qy update && apt-get install -y \
      unzip \
      jq

RUN curl -s -oterraform_0.14.5_linux_amd64.zip https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip \
      && unzip terraform_0.14.5_linux_amd64.zip \
      && rm terraform_0.14.5_linux_amd64.zip \
      && mv terraform /usr/bin

USER user

RUN mkdir -p ~/.config/terraform ~/.config/wildland/templates
