#!/bin/sh -e

if [ -f ~/.config/wildland/users/User.yaml ]; then
    echo "Example data already set up. To recreate, clean up first:"
    echo '  rm -rf ~/storage/*'
    echo '  rm -rf ~/.config/wildland'
    echo
    exit 1
fi

set -x

/home/user/wildland-client/docker/smoke-test/setup.sh

if [ $$ = 1 ]; then
    cd "$MOUNT_DIR"
    exec bash
fi
