#!/usr/bin/env sh

set -ex

# Benchmark:
# (use 'chronic' command from moreutils to suppress output unless the command
# fails)

# Mount all containers
refresh
time -p chronic "$WL_CLI" container mount --with-subcontainers BearDB

# List contents of macro-container
refresh
time -p chronic tree $WL_MOUNT_POINT/bear

# List full Wildland FS contents
refresh
time -p chronic tree $WL_MOUNT_POINT/

# List main directory (readdir)
refresh
time -p chronic ls $WL_MOUNT_POINT/

# List main directory (readdir + getattr)
refresh
time -p chronic ls -l $WL_MOUNT_POINT/

# Remount all containers
refresh
time -p chronic $WL_CLI container mount --with-subcontainers BearDB

# Unmount all containers
refresh
time -p chronic $WL_CLI container unmount --with-subcontainers BearDB
