#!/bin/sh -ex

. /home/user/env/bin/activate
pip install . plugins/*

# Generate a test database
time ./ci/bear-sqlite-generator /tmp/bear.sqlite

# Create a Bear macro-container and mount it
./wl user create User
./wl container create BearDB --path /bear
./wl storage create bear-db --container BearDB --inline --path /tmp/bear.sqlite --trusted
./wl mount
./wl container mount BearDB

# List contents of macro-container
time -p tree $HOME/wildland/bear >/dev/null

# Mount all containers
time -p ./wl container mount $HOME/wildland/bear/*/container.yaml 

# List full Wildland FS contents
time -p tree $HOME/wildland/ >/dev/null
