#!/usr/bin/env sh

set -ex

. /home/user/env/bin/activate
pip install . plugins/*

# Generate a test database
time -p ./ci/bear-sqlite-generator --max-tags=5 /tmp/bear.sqlite

# Create a Bear macro-container and mount it
./wl user create User
./wl container create BearDB --path /bear
./wl storage create bear-db --container BearDB --inline --path /tmp/bear.sqlite --trusted
./wl start

refresh() {
    # TODO: this suppresses errors returned from wlfuse
    echo '{"cmd": "clear-cache"}' | nc -NU $XDG_RUNTIME_DIR/wlfuse.sock >/dev/null
}

# Benchmark:
# (use 'chronic' command from moreutils to suppress output unless the command
# fails)

# Mount all containers
refresh
time -p chronic ./wl container mount --with-subcontainers BearDB

# List contents of macro-container
refresh
time -p chronic tree $HOME/wildland/bear

# List full Wildland FS contents
refresh
time -p chronic tree $HOME/wildland/

# List main directory (readdir)
refresh
time -p chronic ls $HOME/wildland/

# List main directory (readdir + getattr)
refresh
time -p chronic ls -l $HOME/wildland/

# Remount all containers
refresh
time -p chronic ./wl container mount --with-subcontainers BearDB

# Unmount all containers
refresh
time -p chronic ./wl container unmount --with-subcontainers BearDB
