#!/usr/bin/env bash

set -ex

. /home/user/env/bin/activate
. ci/install-inplace

# pytest

pytest -v \
       --cov plugins/categorization_proxy/wildland_categorization_proxy \
       plugins/categorization_proxy
mv /tmp/.coverage.wildland /tmp/.coverage.wildland.pytest