#!/usr/bin/env bash

# Dropbox credentials
ACCESS_TOKEN="$1"
APP_KEY="$2"
REFRESH_TOKEN="$3"

STORAGE_CREDENTIALS="--app-key $APP_KEY --refresh-token $REFRESH_TOKEN"
if [ -n "$ACCESS_TOKEN" ]; then
  STORAGE_CREDENTIALS="--token $ACCESS_TOKEN"
fi

. ci/ci-generic-backend-plugin dropbox $STORAGE_CREDENTIALS
