#!/usr/bin/env bash

set -ex

. /home/user/env/bin/activate
. ci/install-inplace git

WL='python3 -m coverage run -p ./wl --verbose'

#setup
ROOT="$HOME/wildland"
MNT_DIR_1="git-mnt-1"
MNT_DIR_2="git-mnt-2"
MNT_PATH_1="$ROOT/$MNT_DIR_1"
MNT_PATH_2="$ROOT/$MNT_DIR_2"

# Create and mount a Git container
$WL user create git-user
mkdir /tmp/git_repo
$WL container create Git --path "/$MNT_DIR_1"
$WL storage create git --container Git --url https://gitlab.com/wildland/wildland-tutorials.git
$WL start

# List full tree
time -p chronic tree "$ROOT"

# List /wildland directory
time -p chronic ls "$ROOT"

# List contents of the repo directory
time -p chronic ls "$MNT_PATH_1"

# Check contents of the drafts directory for the project
time -p test -d "$MNT_PATH_1"/drafts

# Check whether files are under correct directories
time -p test -f "$MNT_PATH_1"/README.md
time -p test -f "$MNT_PATH_1"/src/scenarios/kartoteka/Kartoteka-HOWTO.md

# Read contents of files
time -p chronic grep 'tutorials' "$MNT_PATH_1"/README.md

# Unmount the container
time -p chronic $WL container unmount Git

# Create and mount a container for a private repo
$WL container create PrivateGit --path "/$MNT_DIR_2"
$WL storage create git --container PrivateGit --url https://gitlab.com/wildland/ci-example-project.git --username wildland-bot --password $PERSONAL_GITLAB_TOKEN
$WL container mount PrivateGit

# Check whether a directory exists
time -p test -d "$MNT_PATH_2"/New\ directory

# Check whether README can be found
time -p test -f "$MNT_PATH_2"/README.md

# Check the contents of the README
time -p chronic grep 'plugin' "$MNT_PATH_2"/README.md

# Unmount the container
time -p chronic $WL container unmount PrivateGit

# Test storage template creation
$WL template create git --url https://gitlab.com/wildland/wildland-tutorials.git git-temp
$WL container create git-template --path /template --template git-temp
$WL container mount git-template

# Verify that the template creation is working
time -p chronic tree "$ROOT"/template

$WL container unmount git-template
