#!/usr/bin/env bash

set -ex

. /home/user/env/bin/activate
pip install . plugins/ipfs/

# IPFS

ipfs init
ipfs config Addresses.Gateway "/ip4/127.0.0.1/tcp/8888" # 8080 is already taken
echo "Starting IPFS daemon: ipfs."
ipfs daemon &

echo "IPFS is running at /ip4/127.0.0.1/tcp/8888"
echo

mkdir -p ~/tmp/ipfs-data/subdir
printf "foo" > ~/tmp/ipfs-data/file
printf "bar" > ~/tmp/ipfs-data/subdir/file

sleep 5
# wait for the daemon to start
while ! ipfs diag sys &>/dev/null; do
  sleep 1
done

HASH=$(ipfs add -r ~/tmp/ipfs-data/ | grep -E 'Qm.{44} ipfs-data$' -o | head -c 46)

# Wildland

wl user create ipfs-user
wl container create ipfs-con --path /ipfs
wl storage create ipfs --container ipfs-con --endpoint-addr "/ip4/127.0.0.1/tcp/8888" --ipfs-hash /ipfs/$HASH ipfs-storage
wl start --container ipfs-con

# Testing

time -p chronic /bin/bash -c '[[ $(cat ~/wildland/ipfs/file) == "foo" ]]'
time -p chronic /bin/bash -c '[[ $(cat ~/wildland/ipfs/subdir/file) == "bar" ]]'

# Test storage-template creation
wl template create ipfs --endpoint-addr "/ip4/127.0.0.1/tcp/8888" --ipfs-hash /ipfs/$HASH ipfs-template
wl container create ipfs-temp --template ipfs-template --path /ipfstem
wl container mount ipfs-temp

# Verify that the template creation works
time -p chronic /bin/bash -c '[[ $(cat ~/wildland/ipfstem/file) == "foo" ]]'
time -p chronic /bin/bash -c '[[ $(cat ~/wildland/ipfstem/subdir/file) == "bar" ]]'
