#!/usr/bin/env bash

set -ex

. /home/user/env/bin/activate
. ci/install-inplace imap

# pytest

pytest -v \
       --cov plugins/imap/wildland_imap \
       plugins/imap
mv /tmp/.coverage.wildland /tmp/.coverage.wildland.pytest

# Setup
ROOT="$HOME/wildland"
MNT_DIR_1="imap-mnt-1"
MNT_PATH_1="$ROOT/$MNT_DIR_1"

# Populate a mailbox with test data
./ci/imap-mail-make /home/user/Maildir ./ci/imap-data.txt

# Create and mount an IMAP container
WL='python3 -m coverage run -p ./wl --verbose'

# Start a mail server
sudo /etc/init.d/dovecot start

sudo chmod 0666 /dev/fuse

$WL user create User
$WL container create  Imap --path "/$MNT_DIR_1"
$WL storage create imap --container Imap --host 127.0.0.1 --login user \
    --password test --trusted --no-ssl
$WL start
$WL container mount --with-subcontainers Imap

# List full tree
time -p chronic tree "$ROOT"

# List contents of a sender dir
time -p chronic ls -l "$ROOT"/users/normal@dev.null/sender/

# List contents of a timeline dir
time -p chronic ls -l "$ROOT"/timeline/2020/02/02

# Read contents of files by different paths
time -p chronic grep 'Test number 1' "$ROOT"/users/normal@dev.null/sender/Test\ 1*/main_body.txt
time -p chronic grep 'zażółć gęślą jaźń' "$ROOT"/users/utf8@dev.null/sender/utf8\ test\ 1*/main_body.txt
time -p chronic grep 'łąka żab' "$ROOT"/users/utf8@dev.null/sender/@folder/INBOX/utf8\ test\ 2*/main_body.txt
time -p chronic grep 'Test number 3' "$ROOT"/timeline/2020/03/03/Test\ 3*/main_body.txt
time -p chronic grep 'zero in topic' "$ROOT"/users/user@here/recipient/zero?test\ 1*/main_body.txt

# For explanation why there's a 0x80 byte here check the comment in imap-data.txt
time -p chronic grep 'zero'$'\x80''in body' "$ROOT"/folder/INBOX/zero\ test\ 2*/main_body.txt

ts=$(stat -c %Y "$ROOT"/folder/INBOX/no\ time*/main_body.txt)
if [ "$ts" != "0" ]; then
  exit 1
fi

# Unmount container
time -p chronic $WL container unmount Imap
