#!/usr/bin/env sh

set -ex

. /home/user/env/bin/activate
pip install . plugins/*
# add --durations=0 to show all times for tests and setup and teardown
pytest -v \
    --cov wildland --cov-report term --cov-report html:artifacts/htmlcov \
    --cov-report xml:artifacts/coverage.xml \
    --junitxml=artifacts/wildland.xml \
    "$@"
