#!/usr/bin/env sh

set -ex

. /home/user/env/bin/activate

python3 -m coverage run -p -m \
    pytest -v \
    --junitxml=artifacts/wildland.xml \
    --ignore=plugins \
    --ignore=wildland/tests/test_transpose.py \
    "$@"
