#!/usr/bin/env bash

set -ex

. /home/user/env/bin/activate
. ci/install-inplace s3

# pytest

pytest -v \
       --cov plugins/s3/wildland_s3 \
       plugins/s3
mv /tmp/.coverage.wildland /tmp/.coverage.wildland.pytest

# Setup
ROOT="$HOME/wildland"
MNT_DIR_1="s3-mnt-1"
MNT_DIR_2="s3-mnt-2"
MNT_PATH_1="$ROOT/$MNT_DIR_1"
MNT_PATH_2="$ROOT/$MNT_DIR_2"
MINIO_DATA_DIR="/tmp/minio-data/the-bucket"

# Minio

curl -so /tmp/minio https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x /tmp/minio
mkdir -p "$MINIO_DATA_DIR"/subdir

printf "foo" > "$MINIO_DATA_DIR"/file
printf "bar" > "$MINIO_DATA_DIR"/subdir/file
printf "copy_me" > "$MINIO_DATA_DIR"/abbott
printf "move_me" > "$MINIO_DATA_DIR"/floating


MINIO_ROOT_USER='dmr' MINIO_ROOT_PASSWORD='/.,/.,/.,' /tmp/minio server --console-address :9001 /tmp/minio-data &

WL='python3 -m coverage run -p ./wl --verbose'

# Wildland

$WL user create s3-user
$WL container create s3-con --path "/$MNT_DIR_1"
$WL storage create s3 --access-key 'dmr' --secret-key '/.,/.,/.,' --container s3-con --s3-url s3://the-bucket/ --endpoint-url 'http://127.0.0.1:9000' s3-storage
$WL start --container s3-con

# Test files

time -p chronic /bin/bash -c '[[ $(cat '$MNT_PATH_1'/file) == "foo" ]]'
time -p chronic /bin/bash -c '[[ $(cat '$MNT_PATH_1'/subdir/file) == "bar" ]]'

time -p chronic /bin/bash -c '[[ $(cat '$MNT_PATH_1'/abbott) == "copy_me" ]]'
time -p chronic /bin/bash -c '[[ $(cat '$MNT_PATH_1'/floating) == "move_me" ]]'

time -p chronic /bin/bash -c '$(cp '$MNT_PATH_1'/abbott '$MNT_PATH_1'/costello)'
time -p chronic /bin/bash -c '$(mv '$MNT_PATH_1'/floating '$MNT_PATH_1'/subdir/im_new)'

time -p chronic /bin/bash -c '[[ $(cat '$MNT_PATH_1'/costello) == "copy_me" ]]'
time -p chronic /bin/bash -c '[[ $(cat '$MNT_PATH_1'/subdir/im_new) == "move_me" ]]'

time -p chronic /bin/bash -c '$(mv '$MNT_PATH_1'/subdir/im_new '$MNT_PATH_1'/subdir/still_same_dir)'
time -p chronic /bin/bash -c '[[ $(cat '$MNT_PATH_1'/subdir/still_same_dir) == "move_me" ]]'

time -p chronic /bin/bash -c '[[ ! -f '$MNT_PATH_1'/floating ]]'
time -p chronic /bin/bash -c '[[ ! -f '$MNT_PATH_1'/subdir/im_new ]]'

time -p chronic /bin/bash -c '$(rm '$MNT_PATH_1'/abbott)'

time -p chronic /bin/bash -c '[[ ! -f ~/wildland/s3/subdir/abbott ]]'

# Creating a storage by utilizing a template

$WL template create s3 --access-key 'dmr' --secret-key '/.,/.,/.,'  --s3-url s3://the-bucket/ --endpoint-url 'http://127.0.0.1:9000' s3-template
$WL container create s3-temp-con --path "/$MNT_DIR_2" --template s3-template
$WL container mount s3-temp-con

tree "$ROOT"

uuid=$($WL container dump s3-temp-con | grep '/.uuid/' | cut -d / -f 3 )

# Creating some files and folders
mkdir -p "$MINIO_DATA_DIR"/$uuid/subdir

printf "foo" > "$MINIO_DATA_DIR"/$uuid/tempfile
printf "bar" > "$MINIO_DATA_DIR"/$uuid/subdir/tempfile
printf "copy_me" > "$MINIO_DATA_DIR"/$uuid/abbott
printf "move_me" > "$MINIO_DATA_DIR"/$uuid/floating

# Waiting so that the watcher can detect the changes
sleep 10

# Testing whether the files and folders appear in the container
time -p test -d "$MNT_PATH_2"
time -p test -d "$MNT_PATH_2"/subdir
time -p test ! -d "$MNT_PATH_2"/s3:/

time -p test -f "$MNT_PATH_2"/tempfile
time -p test -f "$MNT_PATH_2"/subdir/tempfile
time -p test -f "$MNT_PATH_2"/abbott
time -p test -f "$MNT_PATH_2"/floating

# Checking whether a trailing slash is automatically appended to the url entered by the user
./wl container rm s3-temp-con
./wl template create s3 --access-key 'dmr' --secret-key '/.,/.,/.,'  --s3-url s3://the-bucket --endpoint-url 'http://127.0.0.1:9000' s3-template-slash
./wl container create s3-temp-con2 --path "/$MNT_DIR_2" --template s3-template-slash
./wl container mount s3-temp-con2

url=$(./wl container dump s3-temp-con2 | grep 's3_url' | cut -c 13-)
var="s3://the-bucket/"
if [ "$url" != "$var" ]; then exit 1; fi
