#!/usr/bin/env sh

set -ex

# Setup
ROOT="$HOME/wildland"
MNT_DIR_1="sshfs-mnt-1"
MNT_PATH_1="$ROOT/$MNT_DIR_1"
FILES="$HOME/files"

# Prepare for wildland
sudo /usr/sbin/sshd
ssh -oStrictHostKeyChecking=no 127.0.0.1 echo 1
mkdir $FILES

. /home/user/env/bin/activate
. ci/install-inplace sshfs

WL='python3 -m coverage run -p ./wl --verbose'

$WL user create User
$WL container create sshfs --path "/$MNT_DIR_1"
$WL storage create sshfs --container sshfs --host 127.0.0.1 \
     --path ./files --ssh-user user --ssh-identity $HOME/.ssh/id_rsa

# Test the backend
$WL start
$WL container mount sshfs

mkdir ~/files/testdir
echo 1234 > "$FILES"/testdir/testfile

time -p chronic tree "$ROOT"
time -p chronic ls -l "$MNT_PATH_1"/testdir
time -p chronic grep 1234 "$MNT_PATH_1"/testdir/testfile

time -p chronic /bin/sh -c 'echo abcd > '$MNT_PATH_1'/testdir/test2'
time -p chronic grep abcd "$FILES"/testdir/test2

# Test template creation
$WL template create sshfs --host 127.0.0.1 \
     --path ./files --ssh-user user --ssh-identity $HOME/.ssh/id_rsa sshfs-temp
$WL container create sshfs-temp --template sshfs-temp --path /sshfst
$WL container mount sshfs-temp

time -p chronic tree ~/wildland/
time -p chronic ls -l ~/wildland/sshfst/testdir
time -p chronic grep 1234 ~/wildland/sshfst/testdir/testfile
