#!/usr/bin/env bash

set -ex

ROOT="$HOME/wildland"

. /home/user/env/bin/activate
pip install .

mkdir -p /home/user/catalog

# creating an user
./wl user create user1
./wl start

# creating a template and a forest
./wl template create local --location /home/user/catalog mylocal
./wl forest create user1 mylocal

# creating an example container
./wl container create container1 --title "container1" --category /category/one --category /category/two --category /timeline/2021/07/25
./wl storage create static --file "Hello.md=Hello World!" --container container1

# creating another example container
./wl container create container2 --title "container2" --category /category/one --category /category/three --category /timeline/2021/08/16
./wl storage create static --file "Bye.md=Bye World!" --container container2

# creating a transpose container to modify the categories of the containers
./wl container create transpose
./wl storage create transpose --container transpose --reference-container-url wildland::/.manifests: --rules '{"match-with":"/category/one", "replace-with": "/replaced/one"}' --rules '{"match-category-regex": "/timeline", "replace-with": "/t"}' --rules '{"match-category-regex": "/(.*)", "replace-with": "/prefix/\\1"}' --conflict all-apply
 ./wl --debug container mount transpose
 
 tree $ROOT
 
# checking if the modified categories exist
time -p chronic ls $ROOT/prefix
time -p test -d $ROOT/prefix/replaced/one
time -p test -d $ROOT/prefix/t/2021/07/25

# checking category permutations
time -p test -d $ROOT/prefix/replaced/one/@prefix/category/three/container2

# checking if the files can be accessed via the modifies paths
time -p test -f $ROOT/prefix/replaced/one/container1/Hello.md
time -p test -f $ROOT/prefix/t/2021/08/16/container2/Bye.md

# checking the content of the files
time -p chronic grep 'Hello' $ROOT/prefix/category/two/container1/Hello.md

./wl stop
 
