#!/usr/bin/env bash

set -ex

. /home/user/env/bin/activate
. ci/install-inplace webdav

ROOT="$HOME/wildland"
STORAGE="/home/user/storage"
MNT_DIR_1="webdav-mnt-1"
MNT_DIR_2="webdav-mnt-2"
MNT_PATH_1="$ROOT/$MNT_DIR_1"
MNT_PATH_2="$ROOT/$MNT_DIR_2"
CATEGORY_PATH_1="$ROOT/ci-test"

# Setup
mkdir -p "$STORAGE"
sudo /etc/init.d/apache2 start

mkdir -p "$STORAGE"/foo
echo foobar > "$STORAGE"/foo/file1.txt
echo text > "$STORAGE"/file2.txt

WL='python3 -m coverage run -p ./wl'

# Wildland
$WL user create User1
$WL container create Container1 --path "/$MNT_DIR_1" \
                                 --category /ci-test
$WL storage create webdav --container Container1 \
                           --login 'user' \
                           --password 'password' \
                           --url 'http://localhost:8081/'
$WL start

# Test files and directories
tree $ROOT
time -p test -f "$CATEGORY_PATH_1"/Container1/file2.txt
time -p chronic grep 'text' "$CATEGORY_PATH_1"/Container1/file2.txt
time -p test -f "$MNT_PATH_1"/file2.txt
time -p chronic grep 'text' "$MNT_PATH_1"/file2.txt

time -p test -d "$CATEGORY_PATH_1"/Container1/foo
time -p test -d "$MNT_PATH_1"/foo

time -p test -f "$CATEGORY_PATH_1"/Container1/foo/file1.txt
time -p chronic grep 'foobar' "$CATEGORY_PATH_1"/Container1/foo/file1.txt
time -p test -f "$MNT_PATH_1"/foo/file1.txt
time -p chronic grep 'foobar' "$MNT_PATH_1"/foo/file1.txt

# Cleanup
rm -rf "$STORAGE"

# Test template creation
$WL template create webdav --login 'user' \
                            --password 'password' \
                            --url 'http://localhost:8081/' webdav-temp
$WL container create webdav-temp --template webdav-temp --path "/$MNT_DIR_2"
$WL container mount webdav-temp

# Verify the template creation works
tree "$MNT_PATH_2"

$WL stop
