#!/usr/bin/env bash

set -ex

. /home/user/env/bin/activate
. ci/install-inplace

# pytest

pytest -v \
       --cov plugins/zip-archive/wildland_zip \
       plugins/zip-archive
mv /tmp/.coverage.wildland /tmp/.coverage.wildland.pytest
