FROM wildland-client-ci

USER root

RUN apt-get -qy update && apt-get install -y \
  sudo

RUN usermod -G sudo user
RUN sed -i 's/ ALL/ NOPASSWD:ALL/' /etc/sudoers

RUN curl -sL \
  https://github.com/ipfs/go-ipfs/releases/download/v0.7.0/go-ipfs_v0.7.0_linux-amd64.tar.gz \
  -o go-ipfs_v0.7.0_linux-amd64.tar.gz

RUN tar -xf go-ipfs_v0.7.0_linux-amd64.tar.gz
RUN install go-ipfs/ipfs /bin/
RUN rm -rf go-ipfs go-ipfs_v0.7.0_linux-amd64.tar.gz

EXPOSE 8080

USER user
