FROM wildland-client-ci

USER root

# Run update && install as one command:
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get
RUN apt-get -qy update && apt-get install -y \
      apache2 \
      sudo

# Enable sudo

RUN usermod -G sudo user
RUN sed -i 's/ ALL/ NOPASSWD:ALL/' /etc/sudoers

# Setup webdav

RUN htpasswd -cb /home/user/test-webdav-passwords user password
RUN htpasswd -b /home/user/test-webdav-passwords userro passwordro
RUN sed -i 's/www-data/user/' /etc/apache2/envvars
COPY ./ci/apache2-webdav-test.conf /etc/apache2/sites-available/test-webdav.conf
RUN a2enmod dav dav_fs rewrite
RUN a2dissite 000-default
RUN a2ensite test-webdav
RUN mkdir -p /var/lock/apache2
RUN chown -R user /var/lock/apache2

USER user
