version: '3'

services:
  wildland-client-ci:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
    image: wildland-client-ci
    container_name: wildland-client-ci
    privileged: true
    stdin_open: true
    tty: true
    devices:
      - /dev/fuse
    volumes:
      - ..:/home/user/wildland-client:ro
      - ../artifacts/:/home/user/wildland-client/artifacts:rw

  wildland-client-ci-imap:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile-imap
    image: wildland-client-ci-imap
    container_name: wildland-client-ci-imap
    privileged: true
    stdin_open: true
    tty: true
    devices:
      - /dev/fuse
    volumes:
      - ..:/home/user/wildland-client:ro
      - ../artifacts/:/home/user/wildland-client/artifacts:rw

