#!/bin/bash

# See ci/howto-test-lib.bash for docs about the "test framework"

. ci/howto-test-lib.bash

mkdir -p /home/user/storage
sudo /etc/init.d/apache2 start

pip install . plugins/s3/

# Minio

curl -so /tmp/minio https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x /tmp/minio
mkdir -p /tmp/minio-data/the-bucket/subdir

MINIO_ROOT_USER='dmr' MINIO_ROOT_PASSWORD='/.,/.,/.,' /tmp/minio server /tmp/minio-data &

# Howto

run wl user create bob
bob_userid=$(get_userid bob)

wl start

expected="Storage template [demo-s3] created in /home/user/.config/wildland/templates/demo-s3.template.jinja"
run wl storage-template create s3 --s3-url s3://the-bucket/ --manifest-pattern "/{path}.yaml" \
  --access-key 'dmr' --secret-key '/.,/.,/.,' --endpoint-url 'http://127.0.0.1:9000' --access bob demo-s3

expected="Appended to an existing storage template [demo-s3]"
run wl storage-template add s3 --s3-url s3://the-bucket/ --manifest-pattern "/{path}.yaml" \
  --access-key 'dmr' --secret-key '/.,/.,/.,' --endpoint-url 'http://127.0.0.1:9000' --access '*' --read-only demo-s3

expected_pcre="Created base path: s3://the-bucket/.manifests/$UUID_PCRE
Adding storage $UUID_PCRE to container.
Saved container /home/user/.config/wildland/containers/bob-forest-catalog.container.yaml
Adding storage $UUID_PCRE to container.
Saved container /home/user/.config/wildland/containers/bob-forest-catalog.container.yaml
Saved: /home/user/.config/wildland/users/bob.user.yaml"
run wl forest create bob demo-s3

expected_pcre="/tmp/minio-data/the-bucket/.manifests/$UUID_PCRE
├── .manifests.yaml
├── .uuid/
│   └── $UUID_PCRE.yaml
├── forest-owner.yaml
└── s3:/
    └── the-bucket/
        └── .manifests/
            └── $UUID_PCRE/

5 directories, 3 files"
run tree -aF /tmp/minio-data/the-bucket/.manifests/*

expected_pcre="Created: /home/user/.config/wildland/containers/hello-world.container.yaml
publishing container /.uuid/$UUID_PCRE..."
run wl container create hello-world --path /hello/world

wl storage create static --file "Hello.md=Hello World!" --container hello-world
expected_pcre="/tmp/minio-data/the-bucket/.manifests/$UUID_PCRE
├── .manifests.yaml
├── .uuid/
│   ├── $UUID_PCRE.yaml
│   └── $UUID_PCRE.yaml
├── forest-owner.yaml
├── hello/
│   └── world.yaml
└── s3:/
    └── the-bucket/
        └── .manifests/
            └── $UUID_PCRE/

6 directories, 5 files"
run tree -aF /tmp/minio-data/the-bucket/.manifests/*

wl c mount wildland:"$bob_userid:/hello/world":

expected="/home/user/wildland
└── hello
    └── world
        └── Hello.md

2 directories, 1 file"
run tree ~/wildland

expected="Hello World!"
run cat ~/wildland/hello/world/Hello.md
