#!/usr/bin/env python3
# This is a trivial maildir mail injector. Injected emails are always
# from user@here.
# Contents of the message and relevant header values should be
# provided as positional parameters according to the following syntax:
# 
# imap-mail-make <maildir-path> <from-address> <subject> <date> <content>
#
# Example:
#
# imap-mail-make ./Maildir test@whatever Test \
#    'Wed, 19 Aug 2020 14:33:02 +0000' 'This is a test'


import mailbox

from sys import argv
from email.message import EmailMessage
from email.utils import formatdate, make_msgid

mdir = mailbox.Maildir(argv[1])
msg = EmailMessage()
msg['To'] = 'user@here'
msg['From'] = argv[2]
msg['Subject'] = argv[3]
msg['Date'] = argv[4]
msg['Message-ID'] = make_msgid()
msg.set_content(argv[5])
mdir.add(msg)
mdir.close()
